### ISSUE TITLE
How can we generate `two_hop_rates_items` data based on other datasets for in-depth experimental exploration?

### ISSUE THREAD

**Issue by Eaton0** [jackfrost168/CF_Diff#2]
Thanks to the author for his excellent work and open source code. I would like to know how we can generate two_hop_rates_items data based on other datasets. Specifically, I am interested in understanding the methodology and steps required to create this data for the purpose of conducting in-depth experimental exploration. Could you provide data generated code or point me to relevant resources that could help in this process?

**Comment by jackfrost168** [comment]
Sorry for this late reply. We can use simple BFS to get this two hops data. And I also uploaded a scratch of this code.

**Comment by Eaton0** [comment]
> Sorry for this late reply. We can use simple BFS to get this two hops data. And I also uploaded a scratch of this code.

Thank you for your kind reply, it helps me a lot. Your research is very interesting, I will continue to pay attention to your work, thank you again.
